# Generated by Django 2.0.3 on 2018-04-20 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20180410_1152'),
    ]

    operations = [
        migrations.AddField(
            model_name='endereco',
            name='bairro',
            field=models.CharField(default='sem nome', max_length=50, verbose_name='bairro'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='endereco',
            name='cidade',
            field=models.CharField(max_length=50, verbose_name='cidade'),
        ),
        migrations.AlterField(
            model_name='endereco',
            name='estado',
            field=models.CharField(max_length=50, verbose_name='estado'),
        ),
    ]
