# Generated by Django 2.0.3 on 2018-10-27 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20180420_0948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doador',
            name='sexo',
            field=models.CharField(choices=[('F', 'Feminino'), ('M', 'Masculino')], max_length=10),
        ),
    ]
